services:
  backend:
    image: jafber/decoy-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

  frontend:
    image: jafber/decoy-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
